### PR TITLE
Fix window.event implementation

### LINKED ISSUE #3132: new version 16.5.0 causing @testing-library/react to fail with infinite errors
### Basic info:

- **Node.js version:**  14.15.4 
- **jsdom version:** 16.5.0 

### Minimal reproduction case

```js
require("jsdom-global/register");
const React = require("react");
const { render } = require("@testing-library/react");
render(React.createElement("div", null, "Hello World"));
```

Above code is failing with the following error spewing out in console infinitely.

This occur with the new version 16.5.0 that's just published.  Version 16.4.0 works.

```
Error: Uncaught [TypeError: Cannot set property event of #<Window> which has only a getter]
    at reportException (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at innerInvokeEventListeners (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
    at invokeEventListeners (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
    at HTMLUnknownElementImpl._dispatch (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
    at HTMLUnknownElement.dispatchEvent (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
    at Object.invokeGuardedCallbackDev (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/react-dom/17.0.1/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/react-dom/17.0.1/react-dom/cjs/react-dom.development.js:4056:31)
    at commitRootImpl (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/react-dom/17.0.1/react-dom/cjs/react-dom.development.js:23091:9)
    at unstable_runWithPriority (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/scheduler/0.20.1/scheduler/cjs/scheduler.development.js:646:12) TypeError: Cannot set property event of #<Window> which has only a getter
    at restoreAfterDispatch (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/react-dom/17.0.1/react-dom/cjs/react-dom.development.js:3933:24)
    at HTMLUnknownElement.callCallback (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/react-dom/17.0.1/react-dom/cjs/react-dom.development.js:3944:9)
    at HTMLUnknownElement.callTheUserObjectsOperation (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
    at invokeEventListeners (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
    at HTMLUnknownElementImpl._dispatch (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
    at HTMLUnknownElement.dispatchEvent (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/jsdom/16.5.0/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
    at Object.invokeGuardedCallbackDev (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/react-dom/17.0.1/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (/Users/v012n34/dev/jsdom-1/node_modules/.f/_/react-dom/17.0.1/react-dom/cjs/react-dom.development.js:4056:31)
```

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

### PR DESCRIPTION
**Pull request by domenic**
* Return undefined instead of null by default
* Setting window.event replaces the property

Closes #3132.

### CODE REVIEW

**Review by TimothyGu — APPROVED** [review]

File: lib/jsdom/browser/Window.js [hunk 1]
```diff
@@ -441,7 +441,10 @@ function Window(options) {
       return customElementRegistry;
     },
     get event() {
-      return idlUtils.wrapperForImpl(window._currentEvent);
+      return window._currentEvent ? idlUtils.wrapperForImpl(window._currentEvent) : undefined;
+    },
+    set event(value) {
+      Object.defineProperty(window, "event", { configurable: true, enumerable: true, writable: true, value });
```
Comment (ExE-Boss) [inline lib/jsdom/browser/Window.js:447]: <https://github.com/jsdom/jsdom/pull/3137> includes a helper for creating `[Replaceable]` setters.
