### PR TITLE
Fix <style> and <script> parsing to wait for their close tag

### LINKED ISSUE #2123: Could not parse CSS Stylesheet, when inline style tag font-family has space
~~At first I was blaming this on CSSOM, but after some digging it seems like the `content` passed to CSSOM [here](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/HTMLStyleElement-impl.js#L20) is not complete.~~ (seems to be how the parser works)

### Basic info:

- **Node.js version:** v9.2.1
- **jsdom version:** 11.6.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`
<html>
  <head></head>
  <body>
    <style>
    .cool-class {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
    </style>
    <p class="cool-class">
    Hello!
    </p>
  </body>
</html>
`);
```

### Output:

```
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet (jsdom/lib/jsdom/living/helpers/stylesheets.js:23:21)
    at HTMLStyleElementImpl._childTextContentChangeSteps (jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:20:5)
    at TextImpl.replaceData (jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
    at TextImpl.set data [as data] (jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:21:10)
    at JSDOMParse5Adapter.insertText (jsdom/lib/jsdom/browser/parse5-adapter-parsing.js:115:22)
    at module.exports.Parser._insertCharacters (parse5/lib/parser/index.js:558:26)
    at Object.insertCharacters (parse5/lib/parser/index.js:1014:7)
    at module.exports.Parser._processToken (parse5/lib/parser/index.js:607:38)
    at module.exports.Parser._processInputToken (parse5/lib/parser/index.js:639:14)
    at module.exports.Parser._runParsingLoop (parse5/lib/parser/index.js:409:14) 
    .cool-class {
        font-family: "Helvetica
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet (jsdom/lib/jsdom/living/helpers/stylesheets.js:23:21)
    at HTMLStyleElementImpl._childTextContentChangeSteps (jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:20:5)
    at TextImpl.replaceData (jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
    at TextImpl.set data [as data] (jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:21:10)
    at JSDOMParse5Adapter.insertText (jsdom/lib/jsdom/browser/parse5-adapter-parsing.js:115:22)
    at module.exports.Parser._insertCharacters (parse5/lib/parser/index.js:558:26)
    at Object.insertCharacters (parse5/lib/parser/index.js:1014:7)
    at module.exports.Parser._processToken (parse5/lib/parser/index.js:607:38)
    at module.exports.Parser._processInputToken (parse5/lib/parser/index.js:639:14)
    at module.exports.Parser._runParsingLoop (parse5/lib/parser/index.js:409:14) 
    .cool-class {
        font-family: "Helvetica 
```

### How does similar code behave in browsers?

The HTML works fine in browsers, and sets the font properly: https://jsfiddle.net/tveprk11/

---

Removing the space from `"Helvetica Neue"` allows the code to run without errors.

### LINKED ISSUE #2131: Error: Could not parse CSS stylesheet with jsdom 11.6.0
### Basic info:

- **Node.js version:** 8.5.0 (used to find regression range), 9.4.0 used where first detected
- **jsdom version:** 11.6.0 (local testing, on Travis I think it was 11.6.1)

### Minimal reproduction case

```js
'use strict'

const fetch = require('node-fetch'); // 1.7.3
const JSDOM = require('jsdom').JSDOM

async function repro(url) {
  const response = await fetch(url);
  const text = await response.text();
  const document = new JSDOM(text).window.document;
  console.log(document);
  return document;
}

repro('https://web.archive.org/web/20180127184316/https://w3c.github.io/webauthn/')

```

The errors are very verbose, starting with:
```
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:23:21)
    at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:20:5)
    at HTMLStyleElementImpl.insertBefore (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:225:14)
    at HTMLStyleElementImpl.appendChild (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:327:17)
    at JSDOMParse5Adapter.insertText (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/browser/parse5-adapter-parsing.js:119:18)
    at module.exports.Parser._insertCharacters (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:558:26)
    at Object.insertCharacters (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:1014:7)
    at module.exports.Parser._processToken (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:607:38)
    at module.exports.Parser._processInputToken (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:639:14)
    at module.exports.Parser._runParsingLoop (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:409:14) /*
```

https://travis-ci.org/foolip/day-to-day/builds/331681172 is where I first saw it.

https://travis-ci.org/foolip/day-to-day/builds/334160581 is where I "fixed" it by locking to jsdom 11.5.1.

### PR DESCRIPTION
**Pull request by domenic**
This replaces our previous hacky <script>-only close tag detection, which only worked in non-empty <script> cases, with a more general hacky version that works for all elements, including empty elements, by monkeypatching parse5. (Eventually https://github.com/inikulin/parse5/issues/237 should give us a better solution, but for now we lock our parse5 version and monkeypatch it.)

In particular, this allows us to not parse stylesheets before their close tag is encountered, which fixes #2123 and fixes #2131.

### CODE REVIEW

File: lib/jsdom/living/nodes/HTMLScriptElement-impl.js [hunk 1]
```diff
@@ -47,15 +54,13 @@ class HTMLScriptElementImpl extends HTMLElementImpl {
...
-  // and there is interesting child text content, if applicable. Note that both 2a) and 2b) can be true in strange
-  // cases (see e.g. the html/semantics/scripting-1/the-script-element/execution-timing/115.html WPT).
+  _poppedOffStackOfOpenElements() {
+    this._closeTagHasBeenSeen = true;
+    this._eval();
+  }
+
   _eval() {
-    if (!this._attached || this._startedEval) {
+    if ((!this._closeTagHasBeenSeen && this._parserInserted) || !this._attached || this._startedEval) {
```
Comment (TimothyGu) [inline lib/jsdom/living/nodes/HTMLScriptElement-impl.js]: Same as `<style>`: I'd rather the `!this._parserInserted` be placed in `_attach()`. This should also avoid needing to add the `_closeTagHasBeenSeen` flag.

See https://html.spec.whatwg.org/multipage/scripting.html#script-processing-model:parser-inserted-2, which has:

> When a `script` element that is **not marked as being "parser-inserted"** experiences one of the events listed in the following list, the user agent must immediately prepare the script element:
>
> - The `script` element **becomes connected**.
> - ...

File: package.json [hunk 2]
```diff
@@ -30,7 +30,7 @@
     "html-encoding-sniffer": "^1.0.2",
     "left-pad": "^1.2.0",
     "nwmatcher": "^1.4.3",
-    "parse5": "^4.0.0",
+    "parse5": "4.0.0",
```
Comment (Zirro) [inline package.json]: Not sure how Yarn would resolve the difference here, but you might want to update the lockfile as well to be sure.

File: lib/jsdom/living/nodes/HTMLScriptElement-impl.js (hunk 1 above)
Comment (domenic) [reply lib/jsdom/living/nodes/HTMLScriptElement-impl.js]: I was trying to do a more direct translation of pre-8c84ebf3b7f3420b6e6cc68612ed3e0b9c1f4455, but hopefully it works to follow the spec too. Let's give it a shot...

**Comment by domenic** [comment]
Updated with a new commit that goes further in being conformant; PTAL! Also amended first commit to fix yarn.lock.

**Comment by domenic** [comment]
Let me merge this to help our consumers; post-merge review still appreciated.
